config/routes.rb
TestMongo::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}

	match '/auth/:provider/callback' => 'authentications#create'
	resources :authentications, only: [:index, :destroy]


  resources :users, only: [:index, :show] do
  	get '/information/edit' => 'user_informations#edit'
  	put '/information' => 'user_informations#update'
  end
  
  root :to => 'index#index'
end

app/models/authentication.rb
class Authentication
	include Mongoid::Document

	field :provider,  type: String
  field :uid,       type: String
  field :user_id,		type: Integer

  belongs_to :user
  
  def self.provider_exists?(provider)
    where(provider: provider.to_s).exists?
  end

  def provider_name
    if provider == 'open_id'
      "OpenID"
    else
      provider.titleize
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]
  
  ## Database authenticatable
  field :email,               :type => String, :default => ""
  field :encrypted_password,  :type => String, :default => ""
  field :nickname,            :type => String

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  
  validates :nickname, presence: true, uniqueness: true
  
  has_many :authentications, dependent: :destroy
  has_one :user_information, dependent: :destroy

  attr_accessor :login
  
  def to_param
    nickname
  end
  
  def information
    user_information
  end
    
  class << self
    def find_by_slug(slug)
      find_by nickname: slug 
    end

    # method for devise authentication with eamil or nickname
    def find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        self.any_of({ :nickname =>  /^#{Regexp.escape(login)}$/i }, { :email =>  /^#{Regexp.escape(login)}$/i }).first
      else
        super
      end
    end
  end
end

app/models/user_information.rb
class UserInformation
  include Mongoid::Document
 	include Mongoid::MultiParameterAttributes
  
  field :user_id, 	:type => Integer
  field :firstname,	:type => String
  field :lastname,	:type => String
  field :birthday,	:type => Date

  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
    omniauth = request.env["omniauth.auth"]

    authentication = Authentication.where(omniauth.slice(:provider, :uid)).first
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      session[:omniauth] = omniauth.except('extra')
      flash[:notice] = "You don't have #{omniauth[:provider]} authentication!"
      redirect_to new_user_registration_url
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    @user.user_information = UserInformation.create()
    
    if @user.save && session[:omniauth]
      @user.authentications.create(:provider => session[:omniauth]['provider'], :uid => session[:omniauth]['uid'])
    end
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth] and session[:omniauth]['info']['email']
      @user.email = session[:omniauth]['info']['email'] if @user.email.blank?
      @user.nickname = session[:omniauth]['info']['email'][/\w*/] if @user.nickname.blank? 
    end
  end
end

app/controllers/user_informations_controller.rb
class UserInformationsController < ApplicationController
	def edit
		@user_information = current_user.user_information
	end
	
	def update
		@user_information = current_user.user_information
		@user_information.update_attributes(params[:user_information])
		redirect_to current_user
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = UserDecorator.find current_user
  end

  def show
    @user = UserDecorator.find_by_slug params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper 
 def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <div>#{sentence}</div>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/views/authentications/index.html.slim
- unless @authentications.empty?
  div style="overflow:hidden"
    p 
      strong You can sign in to this account using:
    .authentications
      - @authentications.each do |authentication| 
        .authentication
          = image_tag "#{authentication.provider}_32.png", :size => "32x32"
          .provider = authentication.provider_name
          .uid = authentication.uid[0..21]
          = link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove"
      .clear

div
  - if @authentications.count < 3
    div 
      strong Add service to sign in with:
  
  - unless @authentications.provider_exists? :twitter
    a href="/auth/twitter" class="auth_provider"
      = image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter"
      Twitter
  
  - unless @authentications.provider_exists? :google
    a href="/auth/google" class="auth_provider"
      = image_tag "google_64.png", :size => "64x64", :alt => "Google"
      Google

  - unless @authentications.provider_exists? :yahoo
    a href="/auth/yahoo" class="auth_provider"
      = image_tag "yahoo_64.png", :size => "64x64", :alt => "Yahoo"
      Yahoo

app/views/index/index.html.slim
h1 Home page
= flash[:notice]

app/views/layouts/application.html.slim
doctype html
html
  head
    title TestMongo
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

body
  = render 'share/nav_bar'
  .container-fluid
  	.row
    	.span6
    		= yield

app/views/share/_nav_bar.html.slim
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      = link_to 'TEST', root_path, class: 'brand'

      .btn-group.pull-right
        - if user_signed_in?
          a.btn.btn-warning.dropdown-toggle data-toggle="dropdown" href="#"
            = current_user.nickname
            span.caret
          ul.dropdown-menu
            li
              = link_to 'Settings', edit_user_registration_path  
            li
              = link_to 'Authentication', authentications_path  
            li.divider
            li
              = link_to 'Sign Out', destroy_user_session_path, method: 'delete'

        - else
          a.btn.btn-warning.dropdown-toggle data-toggle="dropdown" href="#"
            i.icon-user 
            span.caret
          ul.dropdown-menu
            li
              = link_to 'Sign In', new_user_session_path
            li
              = link_to 'Sign in with Twitter','/auth/twitter'
            li
              = link_to 'Sign in with Google', '/auth/google'
            li
              = link_to 'Sign in with Yahoo', '/auth/yahoo'

            li.divider
            li
              = link_to 'Sign Up', new_user_registration_path

      .nav-collapse
        ul.nav
          li.active
            = link_to 'Home', root_path

app/views/user_informations/_form.html.slim
= form_for @user_information do |f|
	div = f.text_field :firstname, placeholder: 'Firstname'
	div = f.text_field :lastname, placeholder: 'Lastname'
	div = date_select  :user_information, :birthday, { :include_blank => true, :start_year => 1970, :end_year => Time.now.year}
	div = f.submit

app/views/user_informations/edit.html.slim
h3 Edit Information
= render 'form'

app/views/users/index.html.slim
= link_to 'User', @user

app/views/users/show.html.slim
= @user.initials
= @user.birthday

= link_to "Edit information", user_information_edit_path(@user)
hr